### ISSUE TITLE
Loop type

### ISSUE THREAD

**Issue by svinkle** [ladieslearningcode/llc-intro-to-browser-extensions#7]
Thoughts on using [`for...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) instead of the classic `for` loop? It's much easier to explain and understand.

Example, instead of:
```js
for (var i = 0; i < allImages.length; i++) {
  console.log(allImages[i]);
}
```

We'd have:
```js
for (var image of allImages) {
  console.log(image);
}
```

https://github.com/ladieslearningcode/llc-intro-to-browser-extensions/blob/4bce3f98ecc52c0a6aaee38933e1c6086a6c630d/slides-en.html#L1284

/cc @dmilliken @kasslent

**Comment by svinkle** [comment]
After going through the entire deck, I realize making this change would be _a lot_ of work. Perhaps next year. 🙂

**Comment by dmilliken** [comment]
Hey! After code day I'm sure we'll have other revisions that we want to make to the deck, so cc Kass on any other ideas you have! :)
